-- This code is generated by the Average Joe AI mod. For more information, visit:
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template = {
  Faction = "UEF",
  Groups = {
    {
      Locations = { T2AirStagingPlatform = { { 4, 4, 0, }, }, },
      Name = "default",
    },
  },
  Name = "Air staging platform - 01",
  Size = 8,
  Units = { "ueb5202", },
}
