-- This code is generated by the Average Joe AI mod. For more information, visit:
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template = {
  Faction = "UEF",
  Groups = {
    {
      Locations = {
        T1EnergyProduction = { { 5, 3, 0, }, { 1, 3, 0, }, },
        T1GroundDefense = { { 4, 6, 0, }, },
        T1Radar = { { 3, 3, 0, }, },
        Wall = {
          { 3, 1, 0, },
          { 2, 1, 0, },
          { 5, 5, 0, },
          { 4, 7, 0, },
          { 5, 7, 0, },
          { 3, 7, 0, },
          { 4, 1, 0, },
          { 5, 6, 0, },
        },
      },
      Name = "default",
    },
  },
  Name = "Radar - 01",
  Size = 8,
  Units = { "ueb5101", "ueb3101", "ueb1101", "ueb2101", },
}
