-- Minimal Lua-source serializer matching the format produced by
-- lua/Utils.lua's SerializeValue/SerializeTable, but without the engine-only
-- helpers (`table.empty`, `STR_Utf8Len`). Saved chunk files diff cleanly
-- against the existing on-disk layout.

local M = {}

local MAX_INLINE = 80

local function escapeString(s)
    s = s:gsub("\\", "\\\\")
    s = s:gsub('"', '\\"')
    s = s:gsub("\n", "\\n")
    s = s:gsub("\r", "\\r")
    return '"' .. s .. '"'
end

local function isIdentifier(s)
    return type(s) == "string" and s:match("^[A-Za-z_][A-Za-z0-9_]*$")
end

local serializeValue
local function serializeTable(tbl, indent)
    indent = indent or ""
    local innerIndent = indent .. "  "
    local lines = { "{\r\n" }

    local n = #tbl
    for i = 1, n do
        table.insert(lines, string.format("%s%s,\r\n", innerIndent, serializeValue(tbl[i], innerIndent)))
    end

    -- Sort hash-part keys so equivalent tables always serialize identically.
    local keys = {}
    for k in pairs(tbl) do
        local isArrayKey = type(k) == "number" and k >= 1 and k <= n and k == math.floor(k)
        if not isArrayKey then table.insert(keys, k) end
    end
    table.sort(keys, function(a, b) return tostring(a) < tostring(b) end)

    for _, k in ipairs(keys) do
        local key = isIdentifier(k) and k or ("[" .. escapeString(tostring(k)) .. "]")
        table.insert(lines, string.format("%s%s = %s,\r\n", innerIndent, key, serializeValue(tbl[k], innerIndent)))
    end

    table.insert(lines, indent .. "}")
    local serialized = table.concat(lines)

    if #serialized <= MAX_INLINE then
        return (serialized:gsub("%s+", " "))
    end
    return serialized
end

serializeValue = function(val, indent)
    indent = indent or ""
    local t = type(val)
    if t == "string" then return escapeString(val)
    elseif t == "number" or t == "boolean" then return tostring(val)
    elseif t == "table" then return serializeTable(val, indent)
    else return '"<unsupported:' .. t .. '>"'
    end
end

M.serializeValue = serializeValue
M.serializeTable = serializeTable

-- Walls live at chunk-coord cell-corner intersections in memory (the editor
-- shows them centered on their saved coord). The on-disk format expects them
-- shifted -1 on both axes; `loader.lua` applies the matching +1 on load to
-- keep round-trips stable.
local WALL_SAVE_DELTA = -1

--- Build a copy of `template` with every `Wall` location shifted by
--- `WALL_SAVE_DELTA` on both axes. Other identifiers and other fields are
--- shared with the original (no full deep-copy needed — `serializeValue`
--- doesn't mutate).
---@param template LoveBaseChunk
---@return LoveBaseChunk
local function templateForSave(template)
    if not template.Groups then return template end

    local newGroups = {}
    for slot, group in pairs(template.Groups) do
        local locs = group.Locations
        if locs and locs.Wall then
            local newLocs = {}
            for id, list in pairs(locs) do
                if id == "Wall" then
                    local shifted = {}
                    for i, loc in ipairs(list) do
                        shifted[i] = { loc[1] + WALL_SAVE_DELTA, loc[2] + WALL_SAVE_DELTA, loc[3] }
                    end
                    newLocs[id] = shifted
                else
                    newLocs[id] = list
                end
            end
            newGroups[slot] = { Name = group.Name, Locations = newLocs }
        else
            newGroups[slot] = group
        end
    end

    local copy = {}
    for k, v in pairs(template) do copy[k] = v end
    copy.Groups = newGroups
    return copy
end

---@param template LoveBaseChunk
---@return string
function M.serializeTemplate(template)
    return table.concat({
        "-- This code is generated by the Average Joe AI mod. For more information, visit:",
        "-- - https://github.com/Garanas/fa-joe-ai",
        "",
        "---@type JoeBaseChunk",
        "Template = " .. serializeValue(templateForSave(template)),
        "",
    }, "\r\n")
end

return M
