-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Air factories - 01",
  Faction = "UEF",
  Locations = {
    ueb5101 = {
      {
        OffsetY = 23.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 5.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 25.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 27.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 8.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 7.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 24.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 7.5,
      },
    },
    ueb1105 = {
      {
        OffsetY = 6.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 16.5,
      },
    },
    ueb4202 = {
      {
        OffsetY = 16.5,
        OffsetX = 16.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 21.5,
        OffsetX = 23.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 29.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 29.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 23.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 16.5,
      },
    },
    ueb0102 = {
      {
        OffsetY = 6.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 6.5,
      },
    },
    ueb1201 = {
      {
        OffsetY = 10.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 22.5,
        OffsetX = 16.5,
      },
    },
  },
  Units = {
    "ueb5101",
    "ueb1101",
    "ueb1201",
    "ueb0102",
    "ueb1105",
    "ueb4202",
  },
  Size = 32,
}