-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Land factories - 01",
  Faction = "UEF",
  Locations = {
    ueb2101 = {
      {
        OffsetY = 2.5,
        OffsetX = 13.5,
      },
    },
    ueb5101 = {
      {
        OffsetY = 12.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 13.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 13.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 14.5,
      },
    },
    ueb3101 = {
      {
        OffsetY = 13.5,
        OffsetX = 13.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 10.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 11.5,
      },
    },
    ueb0101 = {
      {
        OffsetY = 5.5,
        OffsetX = 5.5,
      },
    },
  },
  Units = {
    "ueb1101",
    "ueb2101",
    "ueb5101",
    "ueb0101",
    "ueb3101",
  },
  Size = 16,
}