-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Land factories - 02",
  Faction = "UEF",
  Locations = {
    ueb1201 = {
      {
        OffsetY = 13.5,
        OffsetX = 6.5,
      },
    },
    ueb1105 = {
      {
        OffsetY = 17.5,
        OffsetX = 12.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 29.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 17.5,
        OffsetX = 10.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 24.5,
      },
      {
        OffsetY = 17.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 22.5,
      },
      {
        OffsetY = 19.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 20.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 30.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 16.5,
      },
    },
    ueb0101 = {
      {
        OffsetY = 16.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 24.5,
        OffsetX = 19.5,
      },
      {
        OffsetY = 24.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 6.5,
      },
    },
    ueb2204 = {
      {
        OffsetY = 22.5,
        OffsetX = 12.5,
      },
    },
    ueb4201 = {
      {
        OffsetY = 25.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 18.5,
      },
    },
    ueb2101 = {
      {
        OffsetY = 28.5,
        OffsetX = 28.5,
      },
    },
    ueb5101 = {
      {
        OffsetY = 1.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 27.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 27.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 31.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 27.5,
        OffsetX = 29.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 29.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 29.5,
      },
    },
    ueb4202 = {
      {
        OffsetY = 13.5,
        OffsetX = 12.5,
      },
    },
    ueb2104 = {
      {
        OffsetY = 15.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 18.5,
      },
    },
  },
  Units = {
    "ueb5101",
    "ueb1101",
    "ueb4202",
    "ueb0101",
    "ueb1201",
    "ueb2104",
    "ueb4201",
    "ueb2204",
    "ueb1105",
    "ueb2101",
  },
  Size = 32,
}