-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Air staging - 01",
  Faction = "UEF",
  Locations = {
    ueb5202 = {
      {
        OffsetY = 4.5,
        OffsetX = 4.5,
      },
    },
  },
  Units = {
    "ueb5202",
  },
  Size = 8,
}