-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Radar - 01",
  Faction = "UEF",
  Locations = {
    ueb1101 = {
      {
        OffsetY = 6.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 4.5,
      },
    },
    ueb5101 = {
      {
        OffsetY = 6.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 7.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 1.5,
      },
    },
    ueb3101 = {
      {
        OffsetY = 4.5,
        OffsetX = 4.5,
      },
    },
  },
  Units = {
    "ueb1101",
    "ueb3101",
    "ueb5101",
  },
  Size = 8,
}