local JoeBuildingIdentifiers = import("/mods/fa-joe-ai/lua/Shared/BaseChunks/JoeBuildingIdentifiers.lua")

local TableInsert = table.insert
local TableSort = table.sort
local TableConcat = table.concat
local StringFormat = string.format

--- Resolves the faction name from a blueprint. Falls back to scanning the categories list when the General block is missing.
---@param blueprint UnitBlueprint
---@return string
local function GetFaction(blueprint)
    if blueprint.General and blueprint.General.FactionName then
        return blueprint.General.FactionName
    end

    if blueprint.Categories then
        for _, category in blueprint.Categories do
            if category == "UEF" or category == "AEON" or category == "CYBRAN" or category == "SERAPHIM" then
                return category
            end
        end
    end

    return "UNKNOWN"
end

--- Exports per-faction footprint data for every JoeBuildingIdentifier via SPEW. Output is a markdown table so it can be pasted directly into a docs file. The full output is also copied to the clipboard for easy sharing.
function Handle()
    local buffer = {}
    local function emit(line)
        SPEW(line)
        TableInsert(buffer, line)
    end

    emit("# Joe AI: building identifier footprint export")
    emit("")
    emit("> _Auto-generated by the `average_joe_ai_export_building_footprints` hotkey (see [lua/ui/Actions/ExportBuildingIdentifierFootprints.lua](../../lua/ui/Actions/ExportBuildingIdentifierFootprints.lua)). Re-run the hotkey in-game to regenerate this table — do not hand-edit it._")
    emit("")
    emit("## How to interpret the columns")
    emit("")
    emit("- `SkirtSizeX` / `SkirtSizeZ` — the **footprint that matters for chunk planning**. This is the rectangle the engine reserves around the structure on the build grid; no other structure may overlap it. **Use these for placing buildings inside a chunk.**")
    emit("- `SkirtOffsetX` / `SkirtOffsetZ` — offset of the skirt rectangle from the unit's center. Combined with the skirt size this gives the actual occupied cells.")
    emit("- `FootprintX` / `FootprintZ` — the smaller rectangle inside the skirt that the structure physically blocks. The ring between the footprint and the skirt is walkable terrain that other units can pass through but where no structure can be built. Mostly informational for our purposes.")
    emit("")
    emit("In short: the *skirt* is the keep-out box used for placement; the *footprint* is the solid mesh inside it. For authoring base chunks we care about the skirt fields.")
    emit("")
    emit("| Identifier | UnitId | Faction | Name | FootprintX | FootprintZ | SkirtSizeX | SkirtSizeZ | SkirtOffsetX | SkirtOffsetZ |")
    emit("|------------|--------|---------|------|-----------:|-----------:|-----------:|-----------:|-------------:|-------------:|")

    local totalRows = 0
    local missingIdentifiers = {}

    for _, identifier in JoeBuildingIdentifiers.MappingOrder do
        local category = JoeBuildingIdentifiers.MapToCategory(identifier)
        local unitIds = EntityCategoryGetUnitList(category)

        local rows = {}
        for _, unitId in unitIds do
            local blueprint = __blueprints[unitId]
            if blueprint then
                local physics = blueprint.Physics or {}
                local footprint = blueprint.Footprint or {}
                TableInsert(rows, {
                    Identifier   = identifier,
                    UnitId       = unitId,
                    Faction      = GetFaction(blueprint),
                    Name         = LOC(blueprint.Description or ""),
                    FootprintX   = footprint.SizeX or 0,
                    FootprintZ   = footprint.SizeZ or 0,
                    SkirtSizeX   = physics.SkirtSizeX or 0,
                    SkirtSizeZ   = physics.SkirtSizeZ or 0,
                    SkirtOffsetX = physics.SkirtOffsetX or 0,
                    SkirtOffsetZ = physics.SkirtOffsetZ or 0,
                })
            end
        end

        if table.getn(rows) == 0 then
            TableInsert(missingIdentifiers, identifier)
        else
            TableSort(rows, function(a, b)
                if a.Faction == b.Faction then
                    return a.UnitId < b.UnitId
                end
                return a.Faction < b.Faction
            end)

            for _, row in rows do
                emit(StringFormat(
                    "| %s | %s | %s | %s | %s | %s | %s | %s | %s | %s |",
                    row.Identifier, row.UnitId, row.Faction, row.Name,
                    tostring(row.FootprintX), tostring(row.FootprintZ),
                    tostring(row.SkirtSizeX), tostring(row.SkirtSizeZ),
                    tostring(row.SkirtOffsetX), tostring(row.SkirtOffsetZ)
                ))
                totalRows = totalRows + 1
            end
        end
    end

    if table.getn(missingIdentifiers) > 0 then
        emit("")
        emit("Identifiers with no matching units:")
        for _, identifier in missingIdentifiers do
            emit("- " .. identifier)
        end
    end

    emit("")
    emit(StringFormat("_End of footprint export — %d rows._", totalRows))

    CopyToClipboard(TableConcat(buffer, "\r\n"))
    print(StringFormat("Joe AI - exported %d building footprint rows to clipboard and game.log", totalRows))
end
