-- This code is generated by the Average Joe AI mod. For more information, visit:
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template = {
  Faction = "UEF",
  Groups = {
    "<unsupported:nil>",
    {
      Locations = {
        T1AirFactory = { { 4, 4, 0, }, },
        T1EnergyProduction = {
          { 1, 9, 0, },
          { 3, 9, 0, },
          { 5, 9, 0, },
          { 7, 9, 0, },
        },
      },
      Name = "Group 2",
    },
    {
      Locations = {
        T1EnergyProduction = { { 5, 12, 0, }, },
        Wall = {
          { 2, 12, 0, },
          { 3, 12, 0, },
          { 1, 12, 0, },
        },
      },
      Name = "Group 3",
    },
  },
  Name = "Air - 01",
  Size = 16,
  Units = { "ueb0101", "ueb1101", "ueb5101", "ueb3101", },
}
