-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunkLocation
Template ={
  Name = "Unnamed template",
  Faction = "UEF",
  Locations = {
    Wall = {
      {
        OffsetY = 13.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 3.5,
      },
    },
    T1LandFactory = {
      {
        OffsetY = 4.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 4.5,
      },
    },
    T1Radar = {
      {
        OffsetY = 15.5,
        OffsetX = 5.5,
      },
    },
    T1EnergyProduction = {
      {
        OffsetY = 9.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 3.5,
      },
    },
  },
  Units = {
    "ueb0101",
    "ueb1101",
    "ueb5101",
    "ueb3101",
  },
  Size = 16,
}