-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Land factories - 02",
  Faction = "UEF",
  Locations = {
    ueb5101 = {
      {
        OffsetY = 1.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 10.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 10.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 7.5,
      },
    },
    ueb0101 = {
      {
        OffsetY = 8.5,
        OffsetX = 8.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 13.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 3.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 11.5,
      },
    },
  },
  Units = {
    "ueb0101",
    "ueb5101",
    "ueb1101",
  },
  Size = 16,
}