-- This code is generated by the Average Joe AI mod. For more information, visit:
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template = {
  Faction = "UEF",
  Groups = {
    {
      Locations = {
        EnergyStorage = { { 2, 7, 0, }, },
        T1AADefense = { { 2, 13, 0, }, },
        T1EnergyProduction = {
          { 2, 9, 0, },
          { 12, 11, 0, },
          { 10, 11, 0, },
          { 8, 11, 0, },
          { 6, 11, 0, },
          { 2, 3, 0, },
        },
        T1LandFactory = { { 9, 6, 0, }, },
        Wall = {
          { 8, 1, 0, },
          { 7, 1, 0, },
          { 6, 1, 0, },
          { 1, 14, 0, },
          { 2, 14, 0, },
          { 3, 14, 0, },
          { 1, 1, 0, },
          { 2, 1, 0, },
          { 2, 11, 0, },
          { 3, 11, 0, },
          { 3, 1, 0, },
          { 1, 11, 0, },
          { 10, 1, 0, },
          { 9, 1, 0, },
          { 12, 1, 0, },
          { 11, 1, 0, },
        },
      },
      Name = "default",
    },
  },
  Name = "Land factory - 02",
  Size = 16,
  Units = {
    "ueb5101",
    "ueb1101",
    "ueb0101",
    "ueb2104",
    "ueb1105",
  },
}
