-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Land factories - 03",
  Faction = "UEF",
  Locations = {
    ueb5101 = {
      {
        OffsetY = 17.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 30.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 30.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 30.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 29.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 17.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 17.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 18.5,
        OffsetX = 3.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 2.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 23.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 9.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 27.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 23.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 21.5,
      },
      {
        OffsetY = 1.5,
        OffsetX = 1.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 21.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 21.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 16.5,
      },
    },
    ueb0101 = {
      {
        OffsetY = 16.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 24.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 24.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 8.5,
      },
    },
    ueb2204 = {
      {
        OffsetY = 15.5,
        OffsetX = 23.5,
      },
    },
    ueb4201 = {
      {
        OffsetY = 28.5,
        OffsetX = 14.5,
      },
    },
    ueb2301 = {
      {
        OffsetY = 17.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 5.5,
      },
    },
    ueb2104 = {
      {
        OffsetY = 15.5,
        OffsetX = 27.5,
      },
    },
    ueb4203 = {
      {
        OffsetY = 6.5,
        OffsetX = 16.5,
      },
    },
  },
  Units = {
    "ueb1101",
    "ueb2204",
    "ueb2104",
    "ueb0101",
    "ueb5101",
    "ueb2301",
    "ueb4201",
    "ueb4203",
  },
  Size = 32,
}