-- This code is generated by the Average Joe AI mod.

---@type AIBaseChunkTemplate
Template ={
  Faction = "UEF",
  Name = "Land factories - 01",
  Units = {
    "ueb5101",
    "ueb3101",
    "ueb1101",
    "ueb0101",
    "ueb4202",
    "ueb5202",
    "ueb1201",
    "ueb1105",
    "ueb4201",
    "ueb2301",
  },
  Locations = {
    ueb1201 = {
      {
        OffsetY = 16.5,
        OffsetX = 16.5,
      },
    },
    ueb1105 = {
      {
        OffsetY = 16.5,
        OffsetX = 20.5,
      },
    },
    ueb5202 = {
      {
        OffsetY = 10.5,
        OffsetX = 16.5,
      },
    },
    ueb0101 = {
      {
        OffsetY = 7.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 7.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 25.5,
        OffsetX = 25.5,
      },
      {
        OffsetY = 25.5,
        OffsetX = 7.5,
      },
    },
    ueb4202 = {
      {
        OffsetY = 22.5,
        OffsetX = 16.5,
      },
    },
    ueb3101 = {
      {
        OffsetY = 14.5,
        OffsetX = 12.5,
      },
    },
    ueb4201 = {
      {
        OffsetY = 16.5,
        OffsetX = 6.5,
      },
    },
    ueb2301 = {
      {
        OffsetY = 16.5,
        OffsetX = 24.5,
      },
    },
    ueb5101 = {
      {
        OffsetY = 28.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 17.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 17.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 28.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 15.5,
        OffsetX = 26.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 20.5,
        OffsetX = 22.5,
      },
      {
        OffsetY = 20.5,
        OffsetX = 28.5,
      },
      {
        OffsetY = 20.5,
        OffsetX = 26.5,
      },
      {
        OffsetY = 20.5,
        OffsetX = 24.5,
      },
      {
        OffsetY = 20.5,
        OffsetX = 8.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 16.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 20.5,
        OffsetX = 10.5,
      },
      {
        OffsetY = 26.5,
        OffsetX = 18.5,
      },
      {
        OffsetY = 18.5,
        OffsetX = 20.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 20.5,
      },
      {
        OffsetY = 16.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 14.5,
        OffsetX = 10.5,
      },
    },
  },
  Size = 32,
}