-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template ={
  Name = "Power with storage - 01",
  Faction = "UEF",
  Locations = {
    Wall = {
      {
        8,
        15,
        0,
      },
      {
        9,
        15,
        0,
      },
      {
        1,
        6,
        0,
      },
      {
        1,
        5,
        0,
      },
      {
        1,
        4,
        0,
      },
      {
        1,
        3,
        0,
      },
      {
        3,
        15,
        0,
      },
      {
        4,
        15,
        0,
      },
      {
        5,
        15,
        0,
      },
      {
        6,
        15,
        0,
      },
      {
        7,
        15,
        0,
      },
      {
        1,
        7,
        0,
      },
    },
    T1EnergyProduction = {
      {
        9,
        7,
        0,
      },
      {
        11,
        5,
        0,
      },
      {
        3,
        3,
        0,
      },
      {
        3,
        5,
        0,
      },
      {
        3,
        7,
        0,
      },
      {
        3,
        13,
        0,
      },
      {
        9,
        3,
        0,
      },
      {
        5,
        13,
        0,
      },
      {
        7,
        13,
        0,
      },
      {
        9,
        13,
        0,
      },
    },
    EnergyStorage = {
      {
        9,
        5,
        0,
      },
    },
  },
  Units = {
    "ueb5101",
    "ueb1101",
    "ueb1105",
  },
  Size = 16,
}