-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template ={
  Name = "Power with shield - 01",
  Faction = "UEF",
  Locations = {
    T2EnergyProduction = {
      {
        11,
        11,
        0,
      },
      {
        5,
        5,
        0,
      },
    },
    Wall = {
      {
        3,
        13,
        0,
      },
      {
        4,
        13,
        0,
      },
      {
        5,
        13,
        0,
      },
      {
        6,
        13,
        0,
      },
      {
        3,
        12,
        0,
      },
      {
        3,
        10,
        0,
      },
      {
        3,
        11,
        0,
      },
    },
    T2ShieldDefense = {
      {
        11,
        5,
        0,
      },
    },
    T2AADefense = {
      {
        5,
        11,
        0,
      },
    },
  },
  Units = {
    "ueb1201",
    "ueb5101",
    "ueb2204",
    "ueb4202",
  },
  Size = 16,
}