-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Power - 01",
  Faction = "UEF",
  Locations = {
    ueb1101 = {
      {
        OffsetY = 2.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 2.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 2.5,
      },
    },
  },
  Units = {
    "ueb1101",
  },
  Size = 8,
}