-- This code is generated by the Average Joe AI mod. For more information, visit:
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template = {
  Faction = "UEF",
  Groups = {
    {
      Locations = {
        T1EnergyProduction = {
          { 5, 2, 0, },
          { 2, 2, 0, },
          { 2, 4, 0, },
          { 5, 4, 0, },
        },
        Wall = {
          { 7, 3, 0, },
          { 7, 2, 0, },
          { 0, 4, 0, },
          { 0, 3, 0, },
          { 0, 2, 0, },
          { 4, 6, 0, },
          { 7, 4, 0, },
          { 3, 6, 0, },
        },
      },
      Name = "default",
    },
  },
  Name = "Power - 01",
  Size = 8,
  Units = { "ueb5101", "ueb1101", },
}
