-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Strategical missile defense - 01",
  Faction = "UEF",
  Locations = {
    ueb2101 = {
      {
        OffsetY = 10.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 6.5,
      },
    },
    ueb5101 = {
      {
        OffsetY = 0.5,
        OffsetX = 11.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 6.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 5.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 0.5,
        OffsetX = 10.5,
      },
      {
        OffsetY = 13.5,
        OffsetX = 7.5,
      },
      {
        OffsetY = 9.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 11.5,
        OffsetX = 4.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 5.5,
      },
    },
    ueb4202 = {
      {
        OffsetY = 12.5,
        OffsetX = 12.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 4.5,
      },
    },
    ueb4302 = {
      {
        OffsetY = 6,
        OffsetX = 11,
      },
    },
    ueb2301 = {
      {
        OffsetY = 2.5,
        OffsetX = 11.5,
      },
    },
    ueb4201 = {
      {
        OffsetY = 10.5,
        OffsetX = 6.5,
      },
    },
    ueb2104 = {
      {
        OffsetY = 5.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 14.5,
      },
    },
  },
  Units = {
    "ueb4202",
    "ueb4302",
    "ueb5101",
    "ueb2104",
    "ueb2101",
    "ueb2301",
    "ueb4201",
  },
  Size = 16,
}