-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Gateway - 02",
  Faction = "UEF",
  Locations = {
    ueb0304 = {
      {
        OffsetY = 8.5,
        OffsetX = 9.5,
      },
    },
    ueb1104 = {
      {
        OffsetY = 4.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 8.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 15.5,
      },
      {
        OffsetY = 8.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 3.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 15.5,
      },
    },
  },
  Units = {
    "ueb1104",
    "ueb0304",
  },
  Size = 16,
}