-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template ={
  Name = "Strategic missile defense - 01",
  Faction = "UEF",
  Locations = {
    T2EnergyProduction = {
      {
        5,
        11,
        0,
      },
    },
    T1GroundDefense = {
      {
        3,
        2,
        0,
      },
    },
    T3StrategicMissileDefense = {
      {
        12.5,
        4.5,
        0,
      },
    },
    Wall = {
      {
        2,
        2,
        0,
      },
      {
        1,
        4,
        0,
      },
      {
        1,
        6,
        0,
      },
      {
        1,
        5,
        0,
      },
      {
        4,
        15,
        0,
      },
      {
        5,
        15,
        0,
      },
      {
        6,
        15,
        0,
      },
      {
        7,
        15,
        0,
      },
      {
        2,
        1,
        0,
      },
      {
        4,
        1,
        0,
      },
      {
        3,
        1,
        0,
      },
      {
        15,
        3,
        0,
      },
      {
        15,
        4,
        0,
      },
      {
        15,
        6,
        0,
      },
      {
        15,
        5,
        0,
      },
      {
        3,
        15,
        0,
      },
      {
        4,
        2,
        0,
      },
    },
    T2GroundDefense = {
      {
        3,
        5,
        0,
      },
    },
    T2MissileDefense = {
      {
        7,
        5,
        0,
      },
    },
    T2ShieldDefense = {
      {
        11,
        11,
        0,
      },
    },
  },
  Units = {
    "ueb5101",
    "ueb4201",
    "ueb1201",
    "ueb4202",
    "ueb4302",
    "ueb2301",
    "ueb2101",
  },
  Size = 16,
}