-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type AIBaseChunkTemplate
Template ={
  Name = "Gateway - 01",
  Faction = "UEF",
  Locations = {
    ueb0304 = {
      {
        OffsetY = 8.5,
        OffsetX = 8.5,
      },
    },
    ueb1101 = {
      {
        OffsetY = 4.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 6.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 8.5,
        OffsetX = 2.5,
      },
      {
        OffsetY = 8.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 12.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 10.5,
        OffsetX = 14.5,
      },
      {
        OffsetY = 4.5,
        OffsetX = 14.5,
      },
    },
  },
  Units = {
    "ueb1101",
    "ueb0304",
  },
  Size = 16,
}