-- This code is generated by the Average Joe AI mod. For more information, visit: 
-- - https://github.com/Garanas/fa-joe-ai

---@type JoeBaseChunk
Template ={
  Name = "Air staging platform - 01",
  Faction = "UEF",
  Locations = {
    T2AirStagingPlatform = {
      {
        4,
        4,
        0,
      },
    },
  },
  Units = {
    "ueb5202",
  },
  Size = 8,
}